language: r
r:
  - oldrel
  - release
  - devel
cache: packages
sudo: false
os:
- osx
- linux
osx_image: xcode9
dist: trusty
install: 
  - R -e 'install.packages(c("dplyr", "purrr", "purrrlyr", "Rcpp", "RcppArmadillo))'
