language: r
cache: packages
sudo: false
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - R -e 'install.packages(c("dplyr", "purrr", "tidyr", "Rcpp", "RcppArmadillo", "knitr", "ggplot2", "rmarkdown", "testthat", "covr"))'

after_success:
- Rscript -e 'covr::codecov()'
