language: r
cache: packages
sudo: false
r:
  - oldrel
  - release
  - devel
compiler: gcc

install:
  - R -e 'install.packages(c("dplyr", "purrr", "purrrlyr", "Rcpp", "RcppArmadillo", "knitr", "ggplot2", "rmarkdown", "testthat", "covr"))'

after_success:
- Rscript -e 'covr::codecov()'
